name: Push

on: [push]

jobs:
    build:
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                python-version: [3.5, 3.6, 3.7, 3.8, pypy3]

            fail-fast: true

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install tox tox-gh-actions

            - name: Test on Python ${{ matrix.python-version }}
              run: tox
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    check:
        runs-on: ubuntu-18.04

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install tox
                  python setup.py install

            - name: Clean
              run: tox -e clean
              continue-on-error: true

            - name: Check Distribution
              run: tox -e check_dist
              continue-on-error: true

            - name: Docs
              run: tox -e docs
              continue-on-error: true

            - name: MyPy
              run: tox -e mypy
              continue-on-error: true

            - name: Flake8
              run: tox -e flake8
              continue-on-error: true

            - name: Isort
              run: tox -e isort
              continue-on-error: true

            - name: Black
              run: tox -e Black
              continue-on-error: true
